import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./provider/StoreProvider";
import { ThemeProvider } from 'next-themes'
import Header from "@/shared/layouts/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
            <ThemeProvider 
            attribute="data-theme"  
            defaultTheme={'dark'} 
            enableSystem
            
            >
              <Header/>
              {children}
              {/* <div id="modal-root"></div> */}
            </ThemeProvider>
        </StoreProvider>
     </body>
    </html>
  );
}
