import type { Metadata, Viewport } from "next";
import {manrope} from './fonts'
import "./globals.css";
import StoreProvider from "./provider/StoreProvider";
import { ThemeProvider } from 'next-themes'
import Header from "@/shared/layouts/header/Header";



export const metadata: Metadata = {
  title: "Cubro",
  description: "Generated by create next app",

};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${manrope.variable}`}>
        <StoreProvider>
            <ThemeProvider 
            attribute="data-theme"  
            defaultTheme={'dark'} 
            enableSystem
            
            >
              <Header/>
              {children}
              {/* <div id="modal-root"></div> */}
            </ThemeProvider>
        </StoreProvider>
     </body>
    </html>
  );
}
