services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - next
      - api
    restart: unless-stopped

  next:
    build: ./frontend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=/api   # фронт ходит относительным путём
    restart: unless-stopped

  api:
    build: ./backend
    environment:
      - PORT=8080
      - USE_INMEMORY=true          # ← вместо DATABASE_URL/БД
      # - TG_BOT_TOKEN=...         # если не захардкожен
      # - TG_SECRET_TOKEN=...
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
