services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - next
      - api

  next:
    build: ./frontend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=/api    # фронт ходит относительным путём в /api
    restart: unless-stopped

  api:
    build: ./backend
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://app:pass@db:5432/app?sslmode=disable
    depends_on:
      - db
    restart: unless-stopped

  # db:
  #   image: postgres:16
  #   environment:
  #     - POSTGRES_USER=app
  #     - POSTGRES_PASSWORD=pass
  #     - POSTGRES_DB=app
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  pgdata:
